"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bf80yoi%=u&6@mjb$lqg!_37a@#u5bm48mhxrrucjnh92%f8y4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ==============================================================================
# MULTI-TENANCY APPLICATION CONFIGURATION (django-tenants)
# ==============================================================================

SHARED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',
    'django_tenants',  
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'djoser',
    'core',
    'app',
]

TENANT_APPS = [
    'orgs'
]

# Final compiled app list used by standard Django processes
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

SILENCED_SYSTEM_CHECKS = ['auth.E003']
TENANT_MODEL = "core.Client" 
TENANT_DOMAIN_MODEL = "core.Domain" 
AUTH_USER_MODEL = "core.User"

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': "django_tenants.postgresql_backend",
        'USER': 'postgres',
        'HOST': 'orgs-db',
        'PASSWORD': 'postgres',
        'NAME': 'orgsdb',
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)


# ==============================================================================
# INTERNATIONALIZATION & LOCALIZATION
# ==============================================================================

LANGUAGE_CODE = 'pt'  # Consolidated to your intended default
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LANGUAGES = (
    ('pt', 'Portuguese'),
    ('fr', 'French'),
    ('en', 'English'),
)

MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('pt',),  
    'pt': ('en',),      
}


# ==============================================================================
# SECURITY & AUTHENTICATION VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTHENTICATION_BACKENDS = [
    'core.backends.TenantEmailOrPhoneBackend', 
]


# ==============================================================================
# STATIC & MEDIA FILES
# ==============================================================================

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# REST FRAMEWORK, JWT & DJOSER CONFIGURATION
# ==============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), 
    'AUTH_HEADER_TYPES': ('JWT',),

}

DJOSER = {
    'TOKEN_MODEL': None,
    'LOGIN_FIELD': 'email', 
    'PASSWORD_RESET_CONFIRM_URL': '#/password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    "EMAIL": {
        "password_reset": "core.emails.TenantRoleBasedPasswordResetEmail",
    },
    'SERIALIZERS': {
        "jwt_create": "core.serializers.TenantJWTCreateSerialize",
        "user_create": "core.serializers.TenantUserCreateSerializer",
        "current_user": "djoser.serializers.UserSerializer",
        "set_password": "core.serializers.TenantSetPasswordSerializer",
        "password_reset_confirm": "core.serializers.TenantPasswordResetConfirmSerializer",
    }, 
}


# ==============================================================================
# DOMAIN VARIABLES FOR LOCAL DEVELOPMENT
# ==============================================================================

PUBLIC_DOMAIN = "localhost"
BRIDGE_DOMAIN = "bridge.localhost"
