# Generated by Django 5.0 on 2026-08-11 10:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('registered', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('address_pt', models.CharField(max_length=255, null=True)),
                ('address_en', models.CharField(max_length=255, null=True)),
                ('address_fr', models.CharField(max_length=255, null=True)),
                ('number_of_associated', models.IntegerField()),
                ('picture', models.FileField(upload_to='orgs_api/cms/association_images')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('text_file', models.FileField(upload_to='orgs_api/cms/docs/documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('B', 'Budget'), ('R', 'Report'), ('L', 'Law')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('description_pt', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('picture', models.FileField(upload_to='orgs_api/cms/catalog/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_pt', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('picture', models.FileField(null=True, upload_to='orgs_api/cms/posts/images/')),
                ('text_file', models.FileField(upload_to='orgs_api/cms/posts/documents/')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('picture', models.FileField(upload_to='orgs_api/cms/partner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('link', models.URLField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='orgs_api/cms/video_images/')),
                ('is_band', models.BooleanField(default=False)),
                ('is_spot', models.BooleanField(default=False)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='YearGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('label', models.CharField(default='Metric', max_length=255)),
                ('label_pt', models.CharField(default='Metric', max_length=255, null=True)),
                ('label_en', models.CharField(default='Metric', max_length=255, null=True)),
                ('label_fr', models.CharField(default='Metric', max_length=255, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('show_in_dashboard', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='orgs_api/cms/association_images/')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_images', to='orgs.association')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('key_pt', models.CharField(max_length=255, null=True)),
                ('key_en', models.CharField(max_length=255, null=True)),
                ('key_fr', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255)),
                ('value_pt', models.CharField(max_length=255, null=True)),
                ('value_en', models.CharField(max_length=255, null=True)),
                ('value_fr', models.CharField(max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='orgs.catalogitem')),
            ],
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orgs.category'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cms_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_associations', to='orgs.district'),
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='orgs_api/cms/extras/images/')),
                ('extra_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_extra_images', to='orgs.extradoc')),
            ],
        ),
        migrations.CreateModel(
            name='PageContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Rich Text / HTML'), ('hero', 'Hero Banner'), ('process', 'Step-by-Step / Process / Timeline')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_pt', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_pt', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_fr', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='orgs_api/cms/pages/blocks/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='orgs.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_pt', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('picture', models.FileField(upload_to='orgs_api/cms/posts/images/')),
                ('text_file', models.FileField(blank=True, max_length=500, null=True, upload_to='orgs_api/cms/posts/documents/')),
                ('processed_text_file', models.FileField(blank=True, help_text='Auto-generated JSON file with processed HTML content', max_length=500, null=True, upload_to='orgs_api/cms/posts/processed/')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('is_a_service', models.BooleanField(default=False)),
                ('is_social_service', models.BooleanField(default=False)),
                ('is_to_front', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_pt', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('text_pt', models.TextField(blank=True, null=True)),
                ('text_en', models.TextField(blank=True, null=True)),
                ('text_fr', models.TextField(blank=True, null=True)),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='orgs.blogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_pt', models.CharField(max_length=255, null=True)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('question_fr', models.CharField(max_length=255, null=True)),
                ('information', models.TextField()),
                ('information_pt', models.TextField(null=True)),
                ('information_en', models.TextField(null=True)),
                ('information_fr', models.TextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='orgs.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='orgs_api/cms/post/documents/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orgs.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orgs_api/cms/posts/file/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cms_files', to='orgs.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='orgs_api/cms/posts/images/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='orgs.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='orgs.post')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='orgs.video')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orgs.catalogitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('item', 'client')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(null=True, upload_to='orgs_api/cms/team/images/')),
                ('from_assembly', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='orgs.role')),
            ],
            options={
                'unique_together': {('name', 'role')},
            },
        ),
    ]
