# Generated by Django 5.0 on 2026-09-14 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_association_latitude_association_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='picture',
        ),
        migrations.CreateModel(
            name='CatalogItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='orgs_api/cms/catalog/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('is_feature', models.BooleanField(default=False, help_text='Designates if this is the main image used in catalog listings.')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='orgs.catalogitem')),
            ],
        ),
    ]
