
import logging

from djoser import email

from core.models import Domain

logger = logging.getLogger(__name__)


class TenantRoleBasedPasswordResetEmail(email.PasswordResetEmail):
    template_name = "email/password_reset.html"

    def get_context_data(self):
        # 1. Fetch the default context dictionary generated by Djoser
        context = super().get_context_data()
        user = context.get("user")
        
        # Fallback base domain in case database matching fails
        base_domain = "domain.com"

        if user:
            # =====================================================================
            # ROLE 1: USER IS A PLATFORM SUPERUSER
            # =====================================================================
            if user.is_superuser:
                try:
                    # Look up the domain mapped to the 'public' main server schema
                    public_domain_entry = Domain.objects.filter(
                        tenant__schema_name="public"
                    ).first()
                    if public_domain_entry:
                        base_domain = public_domain_entry.domain
                except Exception as e:
                    logger.error(f"Failed to fetch public schema domain for superuser: {e}")

            # =====================================================================
            # ROLE 2: USER IS A STANDARD TENANT / STAFF USER
            # =====================================================================
            elif hasattr(user, "tenant") and user.tenant is not None:
                try:
                    # Look up the domain mapped strictly to this user's tenant FK
                    tenant_domain_entry = (
                        Domain.objects.filter(tenant=user.tenant, is_primary=True).first()
                        or Domain.objects.filter(tenant=user.tenant).first()
                    )
                    if tenant_domain_entry:
                        base_domain = tenant_domain_entry.domain
                    else:
                        # Dynamic string fallback if no explicit Domain record is found
                        base_domain = f"{user.tenant.schema_name}.domain.com"
                except Exception as e:
                    logger.error(f"Failed to resolve custom domain for tenant user: {e}")

        # 2. Extract encrypted security parameters compiled by Djoser
        uid = context.get("uid")
        token = context.get("token")

        context["url"] = "https://domain.com"
        if user.customer_profile.domain:
            # 3. Dynamically assemble the link matching their system role domain profile
            context["url"] = f"{user.customer_profile.domain}/password/reset/confirm/{uid}/{token}"
        return context
